Controllers/AItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AItemsController : Controller
    {
        private C3IT_DOTNET_TESTEntities db = new C3IT_DOTNET_TESTEntities();

        // GET: AItems
        public ActionResult Index()
        {
            var aItems = db.AItems.Include(a => a.ACategory).Include(a => a.Anshuja);
            return View(aItems.ToList());
        }

        // GET: AItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AItem aItem = db.AItems.Find(id);
            if (aItem == null)
            {
                return HttpNotFound();
            }
            return View(aItem);
        }

        // GET: AItems/Create
        public ActionResult Create()
        {
            ViewBag.cat_id = new SelectList(db.ACategories, "cat_id", "cat_name");
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname");
            return View();
        }

        // POST: AItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_item,itname,cat_id,qty,sold_qty,cost,manufacturer,address,telephone,sales_price,user_id")] AItem aItem)
        {
            if (ModelState.IsValid)
            {
                db.AItems.Add(aItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.cat_id = new SelectList(db.ACategories, "cat_id", "cat_name", aItem.cat_id);
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname", aItem.user_id);
            return View(aItem);
        }

        // GET: AItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AItem aItem = db.AItems.Find(id);
            if (aItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.cat_id = new SelectList(db.ACategories, "cat_id", "cat_name", aItem.cat_id);
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname", aItem.user_id);
            return View(aItem);
        }

        // POST: AItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_item,itname,cat_id,qty,sold_qty,cost,manufacturer,address,telephone,sales_price,user_id")] AItem aItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cat_id = new SelectList(db.ACategories, "cat_id", "cat_name", aItem.cat_id);
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname", aItem.user_id);
            return View(aItem);
        }

        // GET: AItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AItem aItem = db.AItems.Find(id);
            if (aItem == null)
            {
                return HttpNotFound();
            }
            return View(aItem);
        }

        // POST: AItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AItem aItem = db.AItems.Find(id);
            db.AItems.Remove(aItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Report()
        {
            var aItems = db.AItems.Include(a => a.ACategory).Include(a => a.Anshuja);
            return View(aItems.ToList());
        }
    }
}

Controllers/AOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AOrdersController : Controller
    {
        private C3IT_DOTNET_TESTEntities db = new C3IT_DOTNET_TESTEntities();

        // GET: AOrders
        public ActionResult Index()
        {
            var aOrders = db.AOrders.Include(a => a.ACustomer).Include(a => a.Anshuja);
            return View(aOrders.ToList());
        }

        // GET: AOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AOrder aOrder = db.AOrders.Find(id);
            if (aOrder == null)
            {
                return HttpNotFound();
            }
            return View(aOrder);
        }

        // GET: AOrders/Create
        public ActionResult Create()
        {
            
            ViewBag.cust_id = new SelectList(db.ACustomers, "cus_Id", "cus_Id");
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname");
            ViewBag.item_id = new SelectList(db.AItems, "id", "id_item");
            return View();
        }

        // POST: AOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,ordname,qty,orddate,duedate,cust_id,status,user_id,item_id")] AOrder aOrder)
        {

            if (ModelState.IsValid)
            {
                // Retrieve the selected item
                var selectedItem = db.AItems.Find(aOrder.item_id);



                if (selectedItem != null)
                {
                    // Calculate the available quantity
                    int availableQty = (int)selectedItem.qty - (int)selectedItem.sold_qty;



                    // Check if the order quantity is less than or equal to the available quantity
                    if (aOrder.qty <= availableQty)
                    {
                        // Increase the sales_qty for the selected item
                        selectedItem.sold_qty += aOrder.qty;
                        db.Entry(selectedItem).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        // Add the order to the database
                        db.AOrders.Add(aOrder);
                        db.SaveChanges();
                        return RedirectToAction("Index");



                    }
                    else
                    {
                        ModelState.AddModelError("qty", $"Order quantity exceeds available quantity ({availableQty} available).");
                    }
                }
                else
                {
                    ModelState.AddModelError("items_id", "Item not found.");
                }
            }
            if (aOrder.orddate < DateTime.Today.Date)
            {
                ModelState.AddModelError("orddate", "Order date cannot be in the past.");
            }



            if (aOrder.duedate < aOrder.orddate)
            {
                ModelState.AddModelError("duedate", "Due date must be on or after the order date.");
            }

            var customers = db.ACustomers.ToList();

            ViewBag.CustomerList = new SelectList(customers, "cus_Id", "cus_Id");
            //ViewBag.cus_id = new SelectList(db.ACustomers, "cus_Id", "cus_Id");
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname", aOrder.user_id);
            ViewBag.item_id = new SelectList(db.AItems, "id", "id_item",aOrder.item_id);


            // Retrieve the qty data from the items table
            var itemQtyList = db.AItems.Select(item => new SelectListItem
            {
                Value = item.id.ToString(),
                Text = item.id.ToString()
            }).ToList();



            ViewBag.ItemQtyList = itemQtyList;



            return View(aOrder);
        }

        // GET: AOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AOrder aOrder = db.AOrders.Find(id);
            if (aOrder == null)
            {
                return HttpNotFound();
            }
            ViewBag.cust_id = new SelectList(db.ACustomers, "cus_Id", "fname", aOrder.cust_id);
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname", aOrder.user_id);
            return View(aOrder);
        }

        // POST: AOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,ordname,qty,orddate,duedate,cust_id,status,user_id")] AOrder aOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cust_id = new SelectList(db.ACustomers, "cus_Id", "fname", aOrder.cust_id);
            ViewBag.user_id = new SelectList(db.Anshujas, "Id", "fname", aOrder.user_id);
            return View(aOrder);
        }

        // GET: AOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AOrder aOrder = db.AOrders.Find(id);
            if (aOrder == null)
            {
                return HttpNotFound();
            }
            return View(aOrder);
        }

        // POST: AOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AOrder aOrder = db.AOrders.Find(id);
            db.AOrders.Remove(aOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/AnshujasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Data;
namespace WebApplication1.Controllers
{
    public class AnshujasController : Controller
    {
        private C3IT_DOTNET_TESTEntities db = new C3IT_DOTNET_TESTEntities();

        // GET: Anshujas
        public ActionResult Index()
        {
            return View(db.Anshujas.ToList());
        }
        
        public ActionResult Login()
        {
            return View();
        }



        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Login([Bind(Include = "email, password")] Anshuja myUser)
        {
            // Check if a user with the provided email exists in the database
            Anshuja myUser1 = db.Anshujas.FirstOrDefault(u => u.email == myUser.email);



            if (myUser1 != null)
            {
                // Check if the password matches
                if (myUser1.password == myUser.password)
                {
                    if (myUser1.user_level == "admin")
                    {
                        return View("welcome");
                    }
                    else if (myUser1.user_level == "salesperson")
                    {
                        return View("salesWelcome");
                    }
                }
                else
                {
                    // Password is incorrect
                    ModelState.AddModelError("password", "Incorrect Password. Please try again.");
                }
            }
            else
            {
                // Email is incorrect
                ModelState.AddModelError("email", "Email address is not valid.");
            }
           // if (ModelState.ContainsKey("password"))
           // {
           //     ModelState["password"].Errors.Clear();
          //  }


            return View(myUser);
        }
        // GET: Anshujas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anshuja anshuja = db.Anshujas.Find(id);
            if (anshuja == null)
            {
                return HttpNotFound();
            }
            return View(anshuja);
        }

        // GET: Anshujas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Anshujas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,fname,lname,Attname,dob,gender,email,tel,address,user_level,password,udate")] Anshuja anshuja)
        {
            if (ModelState.IsValid)
            {
                db.Anshujas.Add(anshuja);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            return View(anshuja);
        }

        // GET: Anshujas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anshuja anshuja = db.Anshujas.Find(id);
            if (anshuja == null)
            {
                return HttpNotFound();
            }
            return View(anshuja);
        }

        // POST: Anshujas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,fname,lname,Attname,dob,gender,email,tel,address,user_level,password,udate")] Anshuja anshuja)
        {
            if (ModelState.IsValid)
            {
                db.Entry(anshuja).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(anshuja);
        }

        // GET: Anshujas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Anshuja anshuja = db.Anshujas.Find(id);
            if (anshuja == null)
            {
                return HttpNotFound();
            }
            return View(anshuja);
        }

        // POST: Anshujas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Anshuja anshuja = db.Anshujas.Find(id);
            db.Anshujas.Remove(anshuja);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Logout()
        {
            return View();
        }

    }
}

Views/Anshujas/Create.cshtml
@model WebApplication1.Models.Anshuja

@{
    ViewBag.Title = "Create";
}

<h2>Add new User</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Attname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Attname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control",@type="date" } })
                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.udate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.udate, new { htmlAttributes = new { @class = "form-control",@type="date" } })
                @Html.ValidationMessageFor(model => model.udate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Anshujas/Login.cshtml
@model WebApplication1.Models.Anshuja

@{
    ViewBag.Title = "Login";
}



<h2>Login</h2>
<!-- Section: Design Block -->
<section class="text-center text-lg-start">
    <style>
        .rounded-t-5 {
            border-top-left-radius: 0.5rem;
            border-top-right-radius: 0.5rem;
        }
    </style>
    <div class="card mb-3" height="100px">
        <div class="row g-0 d-flex align-items-center">
            <div class="col-lg-4 d-none d-lg-flex">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" height="400px" width="500px"
                     class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
            </div>
 
            <div class="col-lg-8">
                <div class="card-body py-5 px-md-5">
                    @using (Html.BeginForm("Login", "Anshujas"))
                    {
                        @Html.AntiForgeryToken()



                        <!-- Email input -->
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Log In into your account</h5>
                        <div class="form-outline mb-4">
                            <label for="Email">Email</label>
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>



                        <!-- Password input -->
                        <div class="form-outline mb-4">
                            <label for="Password">Password</label>
                            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>



                        <!-- Submit button -->
                        <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Section: Design Block -->





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Anshujas/Logout.cshtml

@{
    ViewBag.Title = "Logout";
}

<h2>Logout Succesfully</h2>
<br />

<h5>Do you want to Login Again?</h5>

<div class="nbox" style="padding:10px;width:8%;">
    @Html.ActionLink("Login", "Login", "Anshujas", new { area = "" }, new { @class = "btn btn-success" })
</div>


Views/Anshujas/saleswelcome.cshtml

@{
    ViewBag.Title = "sales welcome";
}

<h2>Welcome Salesperson! You are logged in as a Salesperson</h2>
<br />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
    .nbox {
        border: 1px solid #000;
        margin: 10px;
        box-shadow: 5px 5px 5px 0px rgba(0,0,0,0.3);
        filter: drop-shadow(5px 5px 5px rgba(0,0,0,0.3));
    }
</style>
<div style="display:flex; height:500px">



    <div class="nbox" style="padding:10px;width:50%">
        <center><h4>Category</h4></center>
        <br />
        <br /><br /><br /><br />
        <center>
            @Html.ActionLink("Create Category", "Create", "ACategories", null, new { @class = "btn btn-success" })
        </center>
        <br />
        <center>
            @Html.ActionLink("View Category", "Index", "ACategories", null, new { @class = "btn btn-primary" })
        </center>



    </div>
    <div class="nbox" style="padding:10px;width:50%">
        <center> <h4>Customers & Shoppings</h4></center>
        <br /><br /><br /><br /><br />
        <center>
            @Html.ActionLink("Add New Customer", "Create", "ACustomers", null, new { @class = "btn btn-success" })
        </center>
        <br />
        <center>
            @Html.ActionLink("View Customers", "Index", "ACustomers", null, new { @class = "btn btn-primary" })
        </center>


    </div>
    <div class="nbox" style="padding:10px;width:50%">
        <center> <h4>Items</h4></center>
        <br /><br /><br /><br /><br />
        <center>
            @Html.ActionLink("Insert Item", "Create", "AItems", null, new { @class = "btn btn-success" })
        </center>
        <br />
        <center>
            @Html.ActionLink("View Items", "Index", "AItems", null, new { @class = "btn btn-primary" })
        </center>



    </div>
    <div class="nbox" style="padding:10px;width:50%">
        <center> <h4>Reports</h4></center>
        <br /><br /><br /><br /><br />
        <center>
            @Html.ActionLink("Loyal Customers", "LongTermCustomers", "ACustomers", null, new { @class = "btn btn-primary" })
        </center>
        <br />



    </div>





</div>
<br/>
<div> @Html.ActionLink("log out", "Logout", "Anshujas", null, new { @class = "btn btn-danger" })</div>

Views/Anshujas/welcome.cshtml

@{
    ViewBag.Title = " welcome";
}

<h2>Welcome Admin! You are logged in as Administrator</h2>
<br />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
    .nbox {
        border: 1px solid #000;
        margin: 10px;
        box-shadow: 5px 5px 5px 0px rgba(0,0,0,0.3);
        filter: drop-shadow(5px 5px 5px rgba(0,0,0,0.3));
    }
   
</style>
<div style="display:flex; height:500px">



    <div class="nbox" style="padding:10px;width:50%">
        <center><h4>Category</h4></center>
        <br />
        <br /><br /><br /><br />
        <center>
            @Html.ActionLink("Create Category", "Create", "ACategories", null, new { @class = "btn btn-success" })
        </center>
        <br />
        <center>
            @Html.ActionLink("View Category", "Index", "ACategories", null, new { @class = "btn btn-primary" })
        </center>



    </div>
    <div class="nbox" style="padding:10px;width:50%">
        <center> <h4>Items</h4></center>
        <br /><br /><br /><br /><br />
        <center>
            @Html.ActionLink("Insert Item", "Create", "AItems", null, new { @class = "btn btn-success" })
        </center>
        <br />
        <center>
            @Html.ActionLink("View Items", "Index", "AItems", null, new { @class = "btn btn-primary" })
        </center>



    </div>
    <div class="nbox" style="padding:10px;width:50%">
        <center> <h4>Users</h4></center>
        <br/>
        <br /><br /><br /><br />
        <center>
            @Html.ActionLink("Add Users", "Create", "Anshujas", null, new { @class = "btn btn-success" })
        </center>
        <br />
        <center>
            @Html.ActionLink("View Users", "Index", "Anshujas", null, new { @class = "btn btn-primary" })
        </center>



    </div>
    <div class="nbox" style="padding:10px;width:50%">
        <center> <h4>Reports</h4></center>
        <br /><br /><br /><br /><br/>
        <center>
            @Html.ActionLink("Report", "Report", "AItems", null, new { @class = "btn btn-success" })
        </center>
        <br />
       
        <center>
            @Html.ActionLink("Purchase Orders", "Create", "AOrders", null, new { @class = "btn btn-primary" })
        </center>



    </div>





</div>
<br />
<div> @Html.ActionLink("log out", "Logout", "Anshujas", null, new { @class = "btn btn-danger" })</div>
